### ISSUE TITLE
Api:postStats not working

### ISSUE THREAD

**Issue by matthew-st** [matthewthechickenman/topgg-lua#1]
Posting stats about your bot doesn't appear to work. I'll look into this further and comment any further details

**Comment by matthew-st** [comment]
Oh, it was just me being stupid, I'll add a little thing to prevent against this rn

**Comment by matthew-st** [comment]
Still doesn't work, even with my fix.

**Comment by matthew-st** [comment]
The request is made, it could be something with the site migration

**Comment by matthew-st** [comment]
Working through this - fixed a bad request error, now getting forbidden. Haven't commited yet.

**Comment by matthew-st** [comment]
CC: @VoltrexMaster
Could you try and fix the forbidden error, we should be good on posting after that.
It's a confirmed valid token it just doesn't want to work with something, idk

**Comment by alexanderpaolini** [comment]
Fixed!

**Comment by VoltrexKeyva** [comment]
Fixed.

**Comment by alexanderpaolini** [comment]
this is pog
